export default{
  "success":true,
  "result":{
    "data":[
      {
        "brandId":1,
        "categoryId":1,
        "createdAt":1518447650000,
        "id":12,
        "itemNo":"P123456",
        "photos":[
          "https://yzjz-cdn.oss-cn-hangzhou.aliyuncs.com/main-1.jpg",
          "https://yzjz-cdn.oss-cn-hangzhou.aliyuncs.com/main-3.jpg"
        ],
        "price":{
          "diamond":20,
          "originPrice":20,
          "sellPrice":22
        },
        "recommendScore":0,
        "sales":4,
        "shopId":0,
        "skus":[],
        "specs":[
          {
            "key":{
              "keyId":0,
              "keyName":"颜色"
            },
            "values":[
              {
                "valueId":0,
                "valueName":"红色"
              },
              {
                "valueId":1,
                "valueName":"白色"
              }
            ]
          },
          {
            "key":{
              "keyId":1,
              "keyName":"尺寸"
            },
            "values":[
              {
                "valueId":0,
                "valueName":"40"
              },
              {
                "valueId":1,
                "valueName":"41"
              }
            ]
          }
        ],
        "status":2,
        "tags":[
          "热卖",
          "新品"
        ],
        "title":"Nike鞋子2代",
        "updatedAt":1519638960000,
        "vendorId":0,
        "version":5
      }
    ],
    "total":1
  }
};
