const types = {
  UPDATE_CART_DATA: 'UPDATE_CART_DATA',
  UPDATE_CURRENT_CHOSEN: 'UPDATE_CURRENT_CHOSEN',
  READ_CURRENT_CHOSEN_LS: 'READ_CURRENT_CHOSEN_LS',
  UPDATE_CURRENT_EDIT_KDT_ID: 'UPDATE_CURRENT_EDIT_KDT_ID',
  UPDATE_INVALID_GOODS_LIST: 'UPDATE_INVALID_GOODS_LIST',
  CLEAR_INVALID_GOODS_LIST: 'CLEAR_INVALID_GOODS_LIST',
  CLEAR_CURRENT_CHOSEN: 'CLEAR_CURRENT_CHOSEN',
  UPDATE_SHOP_INFO_GOODS_DATA: 'UPDATE_SHOP_INFO_GOODS_DATA',
  UPDATE_IS_LOADING_DATA: 'UPDATE_IS_LOADING_DATA',
  UPDATE_ACTIVITY_INFO: 'UPDATE_ACTIVITY_INFO'
};

export default types;
